#!/bin/bash

release_file=/etc/os-release
logfile=/var/log/updater.log
errorlog=/var/log/updater_errors.log

if grep -q "Arch" $release_file
then 
	# This host based on Arch, run the pacman update command
	sudo pacman -Syu 1>>$logfile 2>>$errorlog
	if [ $? -ne 0 ]
	then
		echo "An error occured, pleach check the $errorlog file."
	fi
fi

if grep -q "Debian" $release_file || grep -q "Ubuntu" $release_fil
then
	# The host is based on Debian or Ubuntu,
	# Run the apt version of the command
	sudo apt update 1>>$logfile 2>>$errorlog
	if [ $? -ne 0 ]
	then
		echo "an error occured, please check the $errorlog file."
	fi
	
fi

# if the system is Redhat base then the command is "sudo dnf upgrade". 
# if its an older version of Redhat. 
# Then use "sudo yum check-update" instead.	
